/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvregistreraRouteImport } from './routes/avregistrera'
import { Route as BestallRouteImport } from './routes/bestall'
import { Route as BlommorRouteImport } from './routes/blommor'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CookiepolicyRouteImport } from './routes/cookiepolicy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ErbjudandeRouteImport } from './routes/erbjudande'
import { Route as FruktkorgForetagRouteImport } from './routes/fruktkorg-foretag'
import { Route as FruktkorgKontorRouteImport } from './routes/fruktkorg-kontor'
import { Route as FruktkorgPaJobbetRouteImport } from './routes/fruktkorg-pa-jobbet'
import { Route as FruktkorgStockholmRouteImport } from './routes/fruktkorg-stockholm'
import { Route as FruktkorgStockholmPrisRouteImport } from './routes/fruktkorg-stockholm-pris'
import { Route as FruktladaRouteImport } from './routes/fruktlada'
import { Route as FruktleveransForetagRouteImport } from './routes/fruktleverans-foretag'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KundportalRouteImport } from './routes/kundportal'
import { Route as OffertforfraganRouteImport } from './routes/offertforfragan'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as ProdukterRouteImport } from './routes/produkter'
import { Route as ProvaFruktkorgRouteImport } from './routes/prova-fruktkorg'
import { Route as ProvkorgRouteImport } from './routes/provkorg'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VaruautomatRouteImport } from './routes/varuautomat'
import { Route as VaruautomaterKaffemaskinRouteImport } from './routes/varuautomater-kaffemaskin'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AfIndexRouteImport } from './routes/af/index'
import { Route as AfDashboardRouteImport } from './routes/af/dashboard'
import { Route as AfLoginRouteImport } from './routes/af/login'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BloggIndexRouteImport } from './routes/blogg/index'
import { Route as JamforTypeRouteImport } from './routes/jamfor/$type'
import { Route as MinaSidorIndexRouteImport } from './routes/mina-sidor/index'
import { Route as MinaSidorOrdrarRouteImport } from './routes/mina-sidor/ordrar'
import { Route as ProduktSlugRouteImport } from './routes/produkt/$slug'
import { Route as AfKundDashboardRouteImport } from './routes/af/kund/dashboard'
import { Route as AfKundLoginRouteImport } from './routes/af/kund/login'
import { Route as BloggCategoryIndexRouteImport } from './routes/blogg/$category/index'
import { Route as BloggCategorySlugRouteImport } from './routes/blogg/$category/$slug'
import { Route as FruktkorgAreaIndexRouteImport } from './routes/fruktkorg/$area/index'
import { Route as FruktkorgAreaIndustryRouteImport } from './routes/fruktkorg/$area/$industry'
import { Route as FruktkorgAnstalldaSizeRouteImport } from './routes/fruktkorg/anstallda/$size'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvregistreraRoute = AvregistreraRouteImport.update({
  id: '/avregistrera',
  path: '/avregistrera',
  getParentRoute: () => rootRouteImport,
} as any)
const BestallRoute = BestallRouteImport.update({
  id: '/bestall',
  path: '/bestall',
  getParentRoute: () => rootRouteImport,
} as any)
const BlommorRoute = BlommorRouteImport.update({
  id: '/blommor',
  path: '/blommor',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiepolicyRoute = CookiepolicyRouteImport.update({
  id: '/cookiepolicy',
  path: '/cookiepolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ErbjudandeRoute = ErbjudandeRouteImport.update({
  id: '/erbjudande',
  path: '/erbjudande',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktkorgForetagRoute = FruktkorgForetagRouteImport.update({
  id: '/fruktkorg-foretag',
  path: '/fruktkorg-foretag',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktkorgKontorRoute = FruktkorgKontorRouteImport.update({
  id: '/fruktkorg-kontor',
  path: '/fruktkorg-kontor',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktkorgPaJobbetRoute = FruktkorgPaJobbetRouteImport.update({
  id: '/fruktkorg-pa-jobbet',
  path: '/fruktkorg-pa-jobbet',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktkorgStockholmRoute = FruktkorgStockholmRouteImport.update({
  id: '/fruktkorg-stockholm',
  path: '/fruktkorg-stockholm',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktkorgStockholmPrisRoute = FruktkorgStockholmPrisRouteImport.update({
  id: '/fruktkorg-stockholm-pris',
  path: '/fruktkorg-stockholm-pris',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktladaRoute = FruktladaRouteImport.update({
  id: '/fruktlada',
  path: '/fruktlada',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktleveransForetagRoute = FruktleveransForetagRouteImport.update({
  id: '/fruktleverans-foretag',
  path: '/fruktleverans-foretag',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KundportalRoute = KundportalRouteImport.update({
  id: '/kundportal',
  path: '/kundportal',
  getParentRoute: () => rootRouteImport,
} as any)
const OffertforfraganRoute = OffertforfraganRouteImport.update({
  id: '/offertforfragan',
  path: '/offertforfragan',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukterRoute = ProdukterRouteImport.update({
  id: '/produkter',
  path: '/produkter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvaFruktkorgRoute = ProvaFruktkorgRouteImport.update({
  id: '/prova-fruktkorg',
  path: '/prova-fruktkorg',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvkorgRoute = ProvkorgRouteImport.update({
  id: '/provkorg',
  path: '/provkorg',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VaruautomatRoute = VaruautomatRouteImport.update({
  id: '/varuautomat',
  path: '/varuautomat',
  getParentRoute: () => rootRouteImport,
} as any)
const VaruautomaterKaffemaskinRoute =
  VaruautomaterKaffemaskinRouteImport.update({
    id: '/varuautomater-kaffemaskin',
    path: '/varuautomater-kaffemaskin',
    getParentRoute: () => rootRouteImport,
  } as any)
const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AfIndexRoute = AfIndexRouteImport.update({
  id: '/af/',
  path: '/af/',
  getParentRoute: () => rootRouteImport,
} as any)
const AfDashboardRoute = AfDashboardRouteImport.update({
  id: '/af/dashboard',
  path: '/af/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AfLoginRoute = AfLoginRouteImport.update({
  id: '/af/login',
  path: '/af/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggIndexRoute = BloggIndexRouteImport.update({
  id: '/blogg/',
  path: '/blogg/',
  getParentRoute: () => rootRouteImport,
} as any)
const JamforTypeRoute = JamforTypeRouteImport.update({
  id: '/jamfor/$type',
  path: '/jamfor/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const MinaSidorIndexRoute = MinaSidorIndexRouteImport.update({
  id: '/mina-sidor/',
  path: '/mina-sidor/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinaSidorOrdrarRoute = MinaSidorOrdrarRouteImport.update({
  id: '/mina-sidor/ordrar',
  path: '/mina-sidor/ordrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktSlugRoute = ProduktSlugRouteImport.update({
  id: '/produkt/$slug',
  path: '/produkt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AfKundDashboardRoute = AfKundDashboardRouteImport.update({
  id: '/af/kund/dashboard',
  path: '/af/kund/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AfKundLoginRoute = AfKundLoginRouteImport.update({
  id: '/af/kund/login',
  path: '/af/kund/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggCategoryIndexRoute = BloggCategoryIndexRouteImport.update({
  id: '/blogg/$category/',
  path: '/blogg/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggCategorySlugRoute = BloggCategorySlugRouteImport.update({
  id: '/blogg/$category/$slug',
  path: '/blogg/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktkorgAreaIndexRoute = FruktkorgAreaIndexRouteImport.update({
  id: '/fruktkorg/$area/',
  path: '/fruktkorg/$area/',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktkorgAreaIndustryRoute = FruktkorgAreaIndustryRouteImport.update({
  id: '/fruktkorg/$area/$industry',
  path: '/fruktkorg/$area/$industry',
  getParentRoute: () => rootRouteImport,
} as any)
const FruktkorgAnstalldaSizeRoute = FruktkorgAnstalldaSizeRouteImport.update({
  id: '/fruktkorg/anstallda/$size',
  path: '/fruktkorg/anstallda/$size',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avregistrera': typeof AvregistreraRoute
  '/bestall': typeof BestallRoute
  '/blommor': typeof BlommorRoute
  '/checkout': typeof CheckoutRoute
  '/cookiepolicy': typeof CookiepolicyRoute
  '/dashboard': typeof DashboardRoute
  '/erbjudande': typeof ErbjudandeRoute
  '/fruktkorg-foretag': typeof FruktkorgForetagRoute
  '/fruktkorg-kontor': typeof FruktkorgKontorRoute
  '/fruktkorg-pa-jobbet': typeof FruktkorgPaJobbetRoute
  '/fruktkorg-stockholm': typeof FruktkorgStockholmRoute
  '/fruktkorg-stockholm-pris': typeof FruktkorgStockholmPrisRoute
  '/fruktlada': typeof FruktladaRoute
  '/fruktleverans-foretag': typeof FruktleveransForetagRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/kundportal': typeof KundportalRoute
  '/offertforfragan': typeof OffertforfraganRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/prova-fruktkorg': typeof ProvaFruktkorgRoute
  '/provkorg': typeof ProvkorgRoute
  '/reset-password': typeof ResetPasswordRoute
  '/varuautomat': typeof VaruautomatRoute
  '/varuautomater-kaffemaskin': typeof VaruautomaterKaffemaskinRoute
  '/villkor': typeof VillkorRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/af/dashboard': typeof AfDashboardRoute
  '/af/login': typeof AfLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jamfor/$type': typeof JamforTypeRoute
  '/mina-sidor/ordrar': typeof MinaSidorOrdrarRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/af/': typeof AfIndexRoute
  '/blogg/': typeof BloggIndexRoute
  '/mina-sidor/': typeof MinaSidorIndexRoute
  '/af/kund/dashboard': typeof AfKundDashboardRoute
  '/af/kund/login': typeof AfKundLoginRoute
  '/blogg/$category/$slug': typeof BloggCategorySlugRoute
  '/fruktkorg/$area/$industry': typeof FruktkorgAreaIndustryRoute
  '/fruktkorg/anstallda/$size': typeof FruktkorgAnstalldaSizeRoute
  '/blogg/$category/': typeof BloggCategoryIndexRoute
  '/fruktkorg/$area/': typeof FruktkorgAreaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avregistrera': typeof AvregistreraRoute
  '/bestall': typeof BestallRoute
  '/blommor': typeof BlommorRoute
  '/checkout': typeof CheckoutRoute
  '/cookiepolicy': typeof CookiepolicyRoute
  '/dashboard': typeof DashboardRoute
  '/erbjudande': typeof ErbjudandeRoute
  '/fruktkorg-foretag': typeof FruktkorgForetagRoute
  '/fruktkorg-kontor': typeof FruktkorgKontorRoute
  '/fruktkorg-pa-jobbet': typeof FruktkorgPaJobbetRoute
  '/fruktkorg-stockholm': typeof FruktkorgStockholmRoute
  '/fruktkorg-stockholm-pris': typeof FruktkorgStockholmPrisRoute
  '/fruktlada': typeof FruktladaRoute
  '/fruktleverans-foretag': typeof FruktleveransForetagRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/kundportal': typeof KundportalRoute
  '/offertforfragan': typeof OffertforfraganRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/prova-fruktkorg': typeof ProvaFruktkorgRoute
  '/provkorg': typeof ProvkorgRoute
  '/reset-password': typeof ResetPasswordRoute
  '/varuautomat': typeof VaruautomatRoute
  '/varuautomater-kaffemaskin': typeof VaruautomaterKaffemaskinRoute
  '/villkor': typeof VillkorRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/af/dashboard': typeof AfDashboardRoute
  '/af/login': typeof AfLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jamfor/$type': typeof JamforTypeRoute
  '/mina-sidor/ordrar': typeof MinaSidorOrdrarRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/admin': typeof AdminIndexRoute
  '/af': typeof AfIndexRoute
  '/blogg': typeof BloggIndexRoute
  '/mina-sidor': typeof MinaSidorIndexRoute
  '/af/kund/dashboard': typeof AfKundDashboardRoute
  '/af/kund/login': typeof AfKundLoginRoute
  '/blogg/$category/$slug': typeof BloggCategorySlugRoute
  '/fruktkorg/$area/$industry': typeof FruktkorgAreaIndustryRoute
  '/fruktkorg/anstallda/$size': typeof FruktkorgAnstalldaSizeRoute
  '/blogg/$category': typeof BloggCategoryIndexRoute
  '/fruktkorg/$area': typeof FruktkorgAreaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avregistrera': typeof AvregistreraRoute
  '/bestall': typeof BestallRoute
  '/blommor': typeof BlommorRoute
  '/checkout': typeof CheckoutRoute
  '/cookiepolicy': typeof CookiepolicyRoute
  '/dashboard': typeof DashboardRoute
  '/erbjudande': typeof ErbjudandeRoute
  '/fruktkorg-foretag': typeof FruktkorgForetagRoute
  '/fruktkorg-kontor': typeof FruktkorgKontorRoute
  '/fruktkorg-pa-jobbet': typeof FruktkorgPaJobbetRoute
  '/fruktkorg-stockholm': typeof FruktkorgStockholmRoute
  '/fruktkorg-stockholm-pris': typeof FruktkorgStockholmPrisRoute
  '/fruktlada': typeof FruktladaRoute
  '/fruktleverans-foretag': typeof FruktleveransForetagRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/kundportal': typeof KundportalRoute
  '/offertforfragan': typeof OffertforfraganRoute
  '/om-oss': typeof OmOssRoute
  '/produkter': typeof ProdukterRoute
  '/prova-fruktkorg': typeof ProvaFruktkorgRoute
  '/provkorg': typeof ProvkorgRoute
  '/reset-password': typeof ResetPasswordRoute
  '/varuautomat': typeof VaruautomatRoute
  '/varuautomater-kaffemaskin': typeof VaruautomaterKaffemaskinRoute
  '/villkor': typeof VillkorRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/af/dashboard': typeof AfDashboardRoute
  '/af/login': typeof AfLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jamfor/$type': typeof JamforTypeRoute
  '/mina-sidor/ordrar': typeof MinaSidorOrdrarRoute
  '/produkt/$slug': typeof ProduktSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/af/': typeof AfIndexRoute
  '/blogg/': typeof BloggIndexRoute
  '/mina-sidor/': typeof MinaSidorIndexRoute
  '/af/kund/dashboard': typeof AfKundDashboardRoute
  '/af/kund/login': typeof AfKundLoginRoute
  '/blogg/$category/$slug': typeof BloggCategorySlugRoute
  '/fruktkorg/$area/$industry': typeof FruktkorgAreaIndustryRoute
  '/fruktkorg/anstallda/$size': typeof FruktkorgAnstalldaSizeRoute
  '/blogg/$category/': typeof BloggCategoryIndexRoute
  '/fruktkorg/$area/': typeof FruktkorgAreaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avregistrera'
    | '/bestall'
    | '/blommor'
    | '/checkout'
    | '/cookiepolicy'
    | '/dashboard'
    | '/erbjudande'
    | '/fruktkorg-foretag'
    | '/fruktkorg-kontor'
    | '/fruktkorg-pa-jobbet'
    | '/fruktkorg-stockholm'
    | '/fruktkorg-stockholm-pris'
    | '/fruktlada'
    | '/fruktleverans-foretag'
    | '/integritetspolicy'
    | '/kontakt'
    | '/kundportal'
    | '/offertforfragan'
    | '/om-oss'
    | '/produkter'
    | '/prova-fruktkorg'
    | '/provkorg'
    | '/reset-password'
    | '/varuautomat'
    | '/varuautomater-kaffemaskin'
    | '/villkor'
    | '/admin/dashboard'
    | '/admin/login'
    | '/af/dashboard'
    | '/af/login'
    | '/blog/$slug'
    | '/jamfor/$type'
    | '/mina-sidor/ordrar'
    | '/produkt/$slug'
    | '/admin/'
    | '/af/'
    | '/blogg/'
    | '/mina-sidor/'
    | '/af/kund/dashboard'
    | '/af/kund/login'
    | '/blogg/$category/$slug'
    | '/fruktkorg/$area/$industry'
    | '/fruktkorg/anstallda/$size'
    | '/blogg/$category/'
    | '/fruktkorg/$area/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avregistrera'
    | '/bestall'
    | '/blommor'
    | '/checkout'
    | '/cookiepolicy'
    | '/dashboard'
    | '/erbjudande'
    | '/fruktkorg-foretag'
    | '/fruktkorg-kontor'
    | '/fruktkorg-pa-jobbet'
    | '/fruktkorg-stockholm'
    | '/fruktkorg-stockholm-pris'
    | '/fruktlada'
    | '/fruktleverans-foretag'
    | '/integritetspolicy'
    | '/kontakt'
    | '/kundportal'
    | '/offertforfragan'
    | '/om-oss'
    | '/produkter'
    | '/prova-fruktkorg'
    | '/provkorg'
    | '/reset-password'
    | '/varuautomat'
    | '/varuautomater-kaffemaskin'
    | '/villkor'
    | '/admin/dashboard'
    | '/admin/login'
    | '/af/dashboard'
    | '/af/login'
    | '/blog/$slug'
    | '/jamfor/$type'
    | '/mina-sidor/ordrar'
    | '/produkt/$slug'
    | '/admin'
    | '/af'
    | '/blogg'
    | '/mina-sidor'
    | '/af/kund/dashboard'
    | '/af/kund/login'
    | '/blogg/$category/$slug'
    | '/fruktkorg/$area/$industry'
    | '/fruktkorg/anstallda/$size'
    | '/blogg/$category'
    | '/fruktkorg/$area'
  id:
    | '__root__'
    | '/'
    | '/avregistrera'
    | '/bestall'
    | '/blommor'
    | '/checkout'
    | '/cookiepolicy'
    | '/dashboard'
    | '/erbjudande'
    | '/fruktkorg-foretag'
    | '/fruktkorg-kontor'
    | '/fruktkorg-pa-jobbet'
    | '/fruktkorg-stockholm'
    | '/fruktkorg-stockholm-pris'
    | '/fruktlada'
    | '/fruktleverans-foretag'
    | '/integritetspolicy'
    | '/kontakt'
    | '/kundportal'
    | '/offertforfragan'
    | '/om-oss'
    | '/produkter'
    | '/prova-fruktkorg'
    | '/provkorg'
    | '/reset-password'
    | '/varuautomat'
    | '/varuautomater-kaffemaskin'
    | '/villkor'
    | '/admin/dashboard'
    | '/admin/login'
    | '/af/dashboard'
    | '/af/login'
    | '/blog/$slug'
    | '/jamfor/$type'
    | '/mina-sidor/ordrar'
    | '/produkt/$slug'
    | '/admin/'
    | '/af/'
    | '/blogg/'
    | '/mina-sidor/'
    | '/af/kund/dashboard'
    | '/af/kund/login'
    | '/blogg/$category/$slug'
    | '/fruktkorg/$area/$industry'
    | '/fruktkorg/anstallda/$size'
    | '/blogg/$category/'
    | '/fruktkorg/$area/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvregistreraRoute: typeof AvregistreraRoute
  BestallRoute: typeof BestallRoute
  BlommorRoute: typeof BlommorRoute
  CheckoutRoute: typeof CheckoutRoute
  CookiepolicyRoute: typeof CookiepolicyRoute
  DashboardRoute: typeof DashboardRoute
  ErbjudandeRoute: typeof ErbjudandeRoute
  FruktkorgForetagRoute: typeof FruktkorgForetagRoute
  FruktkorgKontorRoute: typeof FruktkorgKontorRoute
  FruktkorgPaJobbetRoute: typeof FruktkorgPaJobbetRoute
  FruktkorgStockholmRoute: typeof FruktkorgStockholmRoute
  FruktkorgStockholmPrisRoute: typeof FruktkorgStockholmPrisRoute
  FruktladaRoute: typeof FruktladaRoute
  FruktleveransForetagRoute: typeof FruktleveransForetagRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KontaktRoute: typeof KontaktRoute
  KundportalRoute: typeof KundportalRoute
  OffertforfraganRoute: typeof OffertforfraganRoute
  OmOssRoute: typeof OmOssRoute
  ProdukterRoute: typeof ProdukterRoute
  ProvaFruktkorgRoute: typeof ProvaFruktkorgRoute
  ProvkorgRoute: typeof ProvkorgRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VaruautomatRoute: typeof VaruautomatRoute
  VaruautomaterKaffemaskinRoute: typeof VaruautomaterKaffemaskinRoute
  VillkorRoute: typeof VillkorRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AfDashboardRoute: typeof AfDashboardRoute
  AfLoginRoute: typeof AfLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  JamforTypeRoute: typeof JamforTypeRoute
  MinaSidorOrdrarRoute: typeof MinaSidorOrdrarRoute
  ProduktSlugRoute: typeof ProduktSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AfIndexRoute: typeof AfIndexRoute
  BloggIndexRoute: typeof BloggIndexRoute
  MinaSidorIndexRoute: typeof MinaSidorIndexRoute
  AfKundDashboardRoute: typeof AfKundDashboardRoute
  AfKundLoginRoute: typeof AfKundLoginRoute
  BloggCategorySlugRoute: typeof BloggCategorySlugRoute
  FruktkorgAreaIndustryRoute: typeof FruktkorgAreaIndustryRoute
  FruktkorgAnstalldaSizeRoute: typeof FruktkorgAnstalldaSizeRoute
  BloggCategoryIndexRoute: typeof BloggCategoryIndexRoute
  FruktkorgAreaIndexRoute: typeof FruktkorgAreaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avregistrera': {
      id: '/avregistrera'
      path: '/avregistrera'
      fullPath: '/avregistrera'
      preLoaderRoute: typeof AvregistreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestall': {
      id: '/bestall'
      path: '/bestall'
      fullPath: '/bestall'
      preLoaderRoute: typeof BestallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blommor': {
      id: '/blommor'
      path: '/blommor'
      fullPath: '/blommor'
      preLoaderRoute: typeof BlommorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookiepolicy': {
      id: '/cookiepolicy'
      path: '/cookiepolicy'
      fullPath: '/cookiepolicy'
      preLoaderRoute: typeof CookiepolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erbjudande': {
      id: '/erbjudande'
      path: '/erbjudande'
      fullPath: '/erbjudande'
      preLoaderRoute: typeof ErbjudandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktkorg-foretag': {
      id: '/fruktkorg-foretag'
      path: '/fruktkorg-foretag'
      fullPath: '/fruktkorg-foretag'
      preLoaderRoute: typeof FruktkorgForetagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktkorg-kontor': {
      id: '/fruktkorg-kontor'
      path: '/fruktkorg-kontor'
      fullPath: '/fruktkorg-kontor'
      preLoaderRoute: typeof FruktkorgKontorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktkorg-pa-jobbet': {
      id: '/fruktkorg-pa-jobbet'
      path: '/fruktkorg-pa-jobbet'
      fullPath: '/fruktkorg-pa-jobbet'
      preLoaderRoute: typeof FruktkorgPaJobbetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktkorg-stockholm': {
      id: '/fruktkorg-stockholm'
      path: '/fruktkorg-stockholm'
      fullPath: '/fruktkorg-stockholm'
      preLoaderRoute: typeof FruktkorgStockholmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktkorg-stockholm-pris': {
      id: '/fruktkorg-stockholm-pris'
      path: '/fruktkorg-stockholm-pris'
      fullPath: '/fruktkorg-stockholm-pris'
      preLoaderRoute: typeof FruktkorgStockholmPrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktlada': {
      id: '/fruktlada'
      path: '/fruktlada'
      fullPath: '/fruktlada'
      preLoaderRoute: typeof FruktladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktleverans-foretag': {
      id: '/fruktleverans-foretag'
      path: '/fruktleverans-foretag'
      fullPath: '/fruktleverans-foretag'
      preLoaderRoute: typeof FruktleveransForetagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundportal': {
      id: '/kundportal'
      path: '/kundportal'
      fullPath: '/kundportal'
      preLoaderRoute: typeof KundportalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offertforfragan': {
      id: '/offertforfragan'
      path: '/offertforfragan'
      fullPath: '/offertforfragan'
      preLoaderRoute: typeof OffertforfraganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkter': {
      id: '/produkter'
      path: '/produkter'
      fullPath: '/produkter'
      preLoaderRoute: typeof ProdukterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prova-fruktkorg': {
      id: '/prova-fruktkorg'
      path: '/prova-fruktkorg'
      fullPath: '/prova-fruktkorg'
      preLoaderRoute: typeof ProvaFruktkorgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provkorg': {
      id: '/provkorg'
      path: '/provkorg'
      fullPath: '/provkorg'
      preLoaderRoute: typeof ProvkorgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varuautomat': {
      id: '/varuautomat'
      path: '/varuautomat'
      fullPath: '/varuautomat'
      preLoaderRoute: typeof VaruautomatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varuautomater-kaffemaskin': {
      id: '/varuautomater-kaffemaskin'
      path: '/varuautomater-kaffemaskin'
      fullPath: '/varuautomater-kaffemaskin'
      preLoaderRoute: typeof VaruautomaterKaffemaskinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/af/': {
      id: '/af/'
      path: '/af'
      fullPath: '/af/'
      preLoaderRoute: typeof AfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/af/dashboard': {
      id: '/af/dashboard'
      path: '/af/dashboard'
      fullPath: '/af/dashboard'
      preLoaderRoute: typeof AfDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/af/login': {
      id: '/af/login'
      path: '/af/login'
      fullPath: '/af/login'
      preLoaderRoute: typeof AfLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogg/': {
      id: '/blogg/'
      path: '/blogg'
      fullPath: '/blogg/'
      preLoaderRoute: typeof BloggIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamfor/$type': {
      id: '/jamfor/$type'
      path: '/jamfor/$type'
      fullPath: '/jamfor/$type'
      preLoaderRoute: typeof JamforTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mina-sidor/': {
      id: '/mina-sidor/'
      path: '/mina-sidor'
      fullPath: '/mina-sidor/'
      preLoaderRoute: typeof MinaSidorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mina-sidor/ordrar': {
      id: '/mina-sidor/ordrar'
      path: '/mina-sidor/ordrar'
      fullPath: '/mina-sidor/ordrar'
      preLoaderRoute: typeof MinaSidorOrdrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$slug': {
      id: '/produkt/$slug'
      path: '/produkt/$slug'
      fullPath: '/produkt/$slug'
      preLoaderRoute: typeof ProduktSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/af/kund/dashboard': {
      id: '/af/kund/dashboard'
      path: '/af/kund/dashboard'
      fullPath: '/af/kund/dashboard'
      preLoaderRoute: typeof AfKundDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/af/kund/login': {
      id: '/af/kund/login'
      path: '/af/kund/login'
      fullPath: '/af/kund/login'
      preLoaderRoute: typeof AfKundLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogg/$category/': {
      id: '/blogg/$category/'
      path: '/blogg/$category'
      fullPath: '/blogg/$category/'
      preLoaderRoute: typeof BloggCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogg/$category/$slug': {
      id: '/blogg/$category/$slug'
      path: '/blogg/$category/$slug'
      fullPath: '/blogg/$category/$slug'
      preLoaderRoute: typeof BloggCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktkorg/$area/': {
      id: '/fruktkorg/$area/'
      path: '/fruktkorg/$area'
      fullPath: '/fruktkorg/$area/'
      preLoaderRoute: typeof FruktkorgAreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktkorg/$area/$industry': {
      id: '/fruktkorg/$area/$industry'
      path: '/fruktkorg/$area/$industry'
      fullPath: '/fruktkorg/$area/$industry'
      preLoaderRoute: typeof FruktkorgAreaIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruktkorg/anstallda/$size': {
      id: '/fruktkorg/anstallda/$size'
      path: '/fruktkorg/anstallda/$size'
      fullPath: '/fruktkorg/anstallda/$size'
      preLoaderRoute: typeof FruktkorgAnstalldaSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvregistreraRoute: AvregistreraRoute,
  BestallRoute: BestallRoute,
  BlommorRoute: BlommorRoute,
  CheckoutRoute: CheckoutRoute,
  CookiepolicyRoute: CookiepolicyRoute,
  DashboardRoute: DashboardRoute,
  ErbjudandeRoute: ErbjudandeRoute,
  FruktkorgForetagRoute: FruktkorgForetagRoute,
  FruktkorgKontorRoute: FruktkorgKontorRoute,
  FruktkorgPaJobbetRoute: FruktkorgPaJobbetRoute,
  FruktkorgStockholmRoute: FruktkorgStockholmRoute,
  FruktkorgStockholmPrisRoute: FruktkorgStockholmPrisRoute,
  FruktladaRoute: FruktladaRoute,
  FruktleveransForetagRoute: FruktleveransForetagRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KontaktRoute: KontaktRoute,
  KundportalRoute: KundportalRoute,
  OffertforfraganRoute: OffertforfraganRoute,
  OmOssRoute: OmOssRoute,
  ProdukterRoute: ProdukterRoute,
  ProvaFruktkorgRoute: ProvaFruktkorgRoute,
  ProvkorgRoute: ProvkorgRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VaruautomatRoute: VaruautomatRoute,
  VaruautomaterKaffemaskinRoute: VaruautomaterKaffemaskinRoute,
  VillkorRoute: VillkorRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AfDashboardRoute: AfDashboardRoute,
  AfLoginRoute: AfLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  JamforTypeRoute: JamforTypeRoute,
  MinaSidorOrdrarRoute: MinaSidorOrdrarRoute,
  ProduktSlugRoute: ProduktSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AfIndexRoute: AfIndexRoute,
  BloggIndexRoute: BloggIndexRoute,
  MinaSidorIndexRoute: MinaSidorIndexRoute,
  AfKundDashboardRoute: AfKundDashboardRoute,
  AfKundLoginRoute: AfKundLoginRoute,
  BloggCategorySlugRoute: BloggCategorySlugRoute,
  FruktkorgAreaIndustryRoute: FruktkorgAreaIndustryRoute,
  FruktkorgAnstalldaSizeRoute: FruktkorgAnstalldaSizeRoute,
  BloggCategoryIndexRoute: BloggCategoryIndexRoute,
  FruktkorgAreaIndexRoute: FruktkorgAreaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
