
INSERT INTO public.blog_posts (title, slug, content, excerpt, category, author, published, published_at) VALUES
(
'Fruktkorg Stockholm – komplett guide för företag 2026',
'fruktkorg-stockholm-komplett-guide-2026',
E'# Fruktkorg Stockholm – komplett guide för företag 2026\n\nLetar du efter en **fruktkorg i Stockholm** till kontoret? Vitaminkorgen levererar färska fruktkorgar till över 150 företag i Stockholmsregionen – från Södermalm och Östermalm till Kista, Solna och Sundbyberg.\n\n## Varför välja fruktkorg i Stockholm?\n\nEn fruktkorg på kontoret är en av de mest uppskattade **friskvårdsförmånerna** för anställda. Enligt Skatteverket är fruktkorg en skattefri förmån när den erbjuds hela personalen.\n\n- **Höjer trivseln** – 87% av anställda uppskattar frukt på jobbet\n- **Minskar sockersug** och ohälsosamma mellanmål\n- **Skattefri förmån** för alla anställda\n- **Färsk leverans** måndag–fredag i hela Stockholm\n\n## Priser för fruktkorg Stockholm\n\nVåra fruktkorgar startar från **200 kr/vecka** för en Original-korg som räcker till 5–10 personer. Se [aktuella priser i vår webshop](/produkter).\n\n## Områden vi levererar till i Stockholm\n\nVi kör fri leverans till alla större områden: [Södermalm](/fruktkorg/sodermalm), [Östermalm](/fruktkorg/ostermalm), [Kungsholmen](/fruktkorg/kungsholmen), [Vasastan](/fruktkorg/vasastan), [Solna](/fruktkorg/solna), Kista, Sundbyberg och Nacka.\n\n## Kom igång på 3 minuter\n\n1. [Beställ direkt i webshopen](/produkter)\n2. Välj leveransdag (mån–fre)\n3. Vi levererar första korgen inom 3–5 vardagar\n\n**Ingen bindningstid.** Månadsfaktura med 15 dagars betalningsvillkor.\n\n[Beställ fruktkorg Stockholm →](/bestall)',
'Komplett guide för företag som vill beställa fruktkorg i Stockholm 2026. Priser, leveransområden och skatteregler för friskvårdsförmånen.',
'tips', 'Vitaminkorgen', true, now()
),
(
'Fruktbud Stockholm – snabb leverans av frukt till kontoret',
'fruktbud-stockholm-snabb-leverans-frukt-kontor',
E'# Fruktbud Stockholm – snabb leverans av frukt till kontoret\n\nBehöver ditt företag ett pålitligt **fruktbud i Stockholm**? Vitaminkorgen är Stockholms specialist på fruktbud och veckoleverans av färsk frukt till företag.\n\n## Vad är ett fruktbud?\n\nEtt fruktbud levererar färsk frukt direkt till din arbetsplats – oftast veckovis, samma dag och tid. Vi packar korgen på morgonen och kör ut den innan lunch.\n\n## Fördelar med Vitaminkorgens fruktbud i Stockholm\n\n- **Fast leveransdag** varje vecka – välj mån, tis, ons, tor eller fre\n- **Egen bil, egna chaufförer** – aldrig externa budfirmor\n- **Fri leverans** i hela Stockholm innanför tullarna + kringkommuner\n- **Färsk frukt** direkt från grossist – aldrig lagerhållen\n- **Flexibelt** – pausa, ändra eller säga upp när du vill\n\n## Områden där vårt fruktbud kör\n\n- Innerstan: [Södermalm](/fruktkorg/sodermalm), [Östermalm](/fruktkorg/ostermalm), [Kungsholmen](/fruktkorg/kungsholmen), [Vasastan](/fruktkorg/vasastan), Norrmalm, Gamla stan\n- Söderort: Hammarby Sjöstad, Årsta, Liljeholmen, Globen\n- Västerort: [Solna](/fruktkorg/solna), Sundbyberg, [Alvik](/fruktkorg/alvik), Bromma, Kista\n- Norrort: Danderyd, Täby, Sollentuna\n\n## Beställ fruktbud Stockholm\n\nTesta gratis: [Boka en kostnadsfri provkorg](/provkorg) så kör vi ut en fruktkorg till kontoret utan kostnad.\n\n[Se sortiment och beställ →](/produkter)',
'Vitaminkorgen är fruktbudet i Stockholm som levererar färsk frukt till kontor varje vecka. Egen bil, egen personal, fri leverans.',
'tips', 'Vitaminkorgen', true, now()
),
(
'Vad kostar en fruktkorg i Stockholm? Prisguide 2026',
'vad-kostar-fruktkorg-stockholm-prisguide-2026',
E'# Vad kostar en fruktkorg i Stockholm? Prisguide 2026\n\nEn av de vanligaste frågorna vi får är: **vad kostar en fruktkorg i Stockholm?** Här är en ärlig prisguide utan dolda avgifter.\n\n## Prisexempel för fruktkorg Stockholm\n\n| Korg | Antal frukter | Passar antal anställda | Pris/vecka |\n|------|---------------|------------------------|------------|\n| Original liten | ~25 st | 5–10 pers | från 200 kr |\n| Original stor | ~50 st | 15–25 pers | från 350 kr |\n| Premium | ~40 st, exotisk mix | 10–20 pers | från 450 kr |\n| Banan | ~40 bananer | 10–20 pers | från 180 kr |\n\nSe [alla priser och storlekar](/produkter) i webshopen.\n\n## Vad ingår i priset?\n\n- Färsk frukt handplockad samma morgon\n- Fri leverans i hela Stockholm\n- Snygg korg (tas tillbaka vid nästa leverans)\n- Ingen startavgift, ingen bindningstid\n\n## Så räknar du ut rätt storlek\n\nGenerell tumregel: **2 frukter per person per vecka**. Har ni 25 anställda? Då räcker en Original stor + en Banan-låda.\n\nSe [rekommendation för 25 anställda](/fruktkorg/anstallda/25-anstallda) eller [10 anställda](/fruktkorg/anstallda/10-anstallda).\n\n## Är fruktkorg avdragsgillt i Stockholm?\n\nJa – fruktkorg räknas som **skattefri personalvårdsförmån** enligt Skatteverket. Läs mer i vår guide om [förmånsbeskattning för fruktkorg](/blogg/tips/formansbeskattning-fruktkorg).\n\n[Beställ din fruktkorg →](/bestall)',
'Vad kostar fruktkorg i Stockholm? Vi visar priser för alla storlekar, från 180 kr/vecka. Inga dolda avgifter, ingen bindningstid.',
'tips', 'Vitaminkorgen', true, now()
),
(
'Frukt till kontoret Stockholm – så väljer ni rätt leverantör',
'frukt-till-kontoret-stockholm-valj-ratt-leverantor',
E'# Frukt till kontoret Stockholm – så väljer ni rätt leverantör\n\nSka ni börja med **frukt till kontoret i Stockholm**? Här är checklistan för att välja rätt fruktleverantör.\n\n## 7 saker att titta på när du väljer fruktbud i Stockholm\n\n1. **Egen leveransbil eller externt bud?** Egna chaufförer betyder bättre kontroll på kvaliteten.\n2. **Fast leveransdag?** Ni ska kunna planera kaffe-, lunch- och mötesrutiner runt frukten.\n3. **Bindningstid?** Vi rekommenderar leverantörer utan bindningstid – ni ska inte vara låsta.\n4. **Startavgift eller uppsägningsavgift?** Ska vara noll kronor.\n5. **Färskhet** – kommer frukten direkt från grossist eller från lager?\n6. **Priser i webshop** – transparenta priser slår "kontakta oss för offert".\n7. **Fri leverans i Stockholm** – ingen ska betala extra för att ligga på Södermalm.\n\n## Vad kostar frukt till kontoret?\n\nBudgetera **ca 25–35 kr per anställd och vecka** för en bra fruktkorg. För 20 anställda hamnar ni på ~500–700 kr/vecka. Se vår [prisguide för fruktkorg Stockholm](/blogg/tips/vad-kostar-fruktkorg-stockholm-prisguide-2026).\n\n## Vanliga sorter i våra korgar\n\nÄpplen (Gala, Pink Lady), päron (Conference), bananer, apelsiner, klementiner, kiwi, druvor och säsongsfrukt som nektariner eller plommon på sommaren.\n\nPremium-korgen innehåller dessutom: mango, ananas, granatäpple, blåbär och hallon.\n\n## Bygg en hälsokultur på kontoret\n\nFrukt är bara starten – kombinera med [kaffe & te](/produkter?tab=kaffe) och [snacks](/produkter?tab=snacks) för en komplett kontorsservice.\n\n[Testa gratis provkorg →](/provkorg)',
'Guide för Stockholmsföretag som ska välja fruktleverantör. 7 punkter checklista – bindningstid, färskhet, priser och leveransområde.',
'tips', 'Vitaminkorgen', true, now()
);
